spring:
  cloud:
    function:
      definition: consumeTransactionEvent
    stream:
      bindings:
        consumeTransactionEvent-out-0:
          destination: banking.transaction.000
logging:
  level:
    root: info
    org:
      springframework: info

